web:
  image: nginx:1.12
  ports:
    - "8081:80"
  volumes:
    - ./site:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  image: php:7-fpm
  volumes:
    - ./site:/code
