web:
  image: nginx:1.12
  ports:
    - "8080:80"
  volumes:
    - ./samplephpwebsite:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  dockerfile: docker/DockerfilePhp
  volumes:
    - ./samplephpwebsite:/code
  links:
    - db

db:
  image: mariadb:10.1
  volumes:
    - ./install/create.sql:/docker-entrypoint-initdb.d/create.sql
  environment:
    MYSQL_ROOT_PASSWORD: azerty
  ports:
    - 3306:3306
